services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dd_ops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dd_ops
      - NODE_ENV=production
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: